/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AC_Cerdas;

/**
 *
 * @author M.BAHRIL.I
 */
public class AC_Cerdas_Quiz extends javax.swing.JFrame {

    private boolean stsMesin = false;
    private boolean stsSwing = false;
    private boolean sensor = false;
    private static int suhu = 18;
    
    public AC_Cerdas_Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblstatusmesin = new javax.swing.JLabel();
        lblswing = new javax.swing.JLabel();
        lblsensor = new javax.swing.JLabel();
        lblsuhu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbldeteksi = new javax.swing.JLabel();
        lblhuman = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        barami = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnswing = new javax.swing.JButton();
        btnsuhukurang = new javax.swing.JButton();
        btnpower = new javax.swing.JButton();
        btnsensor = new javax.swing.JButton();
        btnsuhutambah = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sldami = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Status Mesin   :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Swing                :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SUHU     :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Deteksi :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sensor");

        lblstatusmesin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblstatusmesin.setForeground(new java.awt.Color(0, 0, 0));
        lblstatusmesin.setText("ON | OFF");

        lblswing.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblswing.setForeground(new java.awt.Color(0, 0, 0));
        lblswing.setText("ON | OFF");

        lblsensor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblsensor.setForeground(new java.awt.Color(0, 0, 0));
        lblsensor.setText("ON | OFF");

        lblsuhu.setForeground(new java.awt.Color(0, 0, 0));
        lblsuhu.setText("...........");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lbldeteksi.setForeground(new java.awt.Color(0, 0, 0));
        lbldeteksi.setText("N****");

        lblhuman.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldeteksi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblhuman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbldeteksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblhuman))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        barami.setBackground(new java.awt.Color(204, 204, 204));
        barami.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barami, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barami, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblsuhu)
                        .addGap(412, 412, 412))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblstatusmesin))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblswing)))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lblsensor))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblstatusmesin)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblswing)
                        .addComponent(lblsensor))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblsuhu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Swing");

        btnswing.setText("ON | OFF");
        btnswing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnswingActionPerformed(evt);
            }
        });

        btnsuhukurang.setText("<");
        btnsuhukurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuhukurangActionPerformed(evt);
            }
        });

        btnpower.setText("POWER");
        btnpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpowerActionPerformed(evt);
            }
        });

        btnsensor.setText("SENSOR");
        btnsensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsensorActionPerformed(evt);
            }
        });

        btnsuhutambah.setText(">");
        btnsuhutambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuhutambahActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("SUHU");

        sldami.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldamiStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnswing)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnsuhukurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuhutambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sldami, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(btnsensor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpower)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnswing))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsensor)
                                .addComponent(btnpower)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnsuhutambah)
                                    .addComponent(btnsuhukurang)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(sldami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpowerActionPerformed
           if (stsMesin == false){
          stsMesin = true;
          lblstatusmesin.setText("ON");
      }  else{
          stsMesin = false;
          lblstatusmesin.setText("OFF");
          lblswing.setText("OFF");
          lblsensor.setText("OFF");
          lblsuhu.setText("....");
          lbldeteksi.setText("....");
          barami.setValue(0);
          
      } 
    }//GEN-LAST:event_btnpowerActionPerformed

    private void btnswingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnswingActionPerformed
         if(stsMesin==true){
           if (stsSwing == false){
                stsSwing = true;
           lblswing.setText("ON");
            lblsuhu.setText("21°C");
       }  else{
           stsSwing = false;
           lblswing.setText("OFF");
           lblsuhu.setText(".....");
      }
        }
    }//GEN-LAST:event_btnswingActionPerformed

    private void btnsuhukurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuhukurangActionPerformed
          if (stsMesin == false){
       }else{
           stsMesin = true;
           lblsuhu.setText(suhu+"°C");
           --suhu;
           if(suhu <= 18){
               suhu = 18;
           }
           
       }    
    }//GEN-LAST:event_btnsuhukurangActionPerformed

    private void btnsuhutambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuhutambahActionPerformed
      if (stsMesin == false){
       }else{
           stsMesin = true;
           lblsuhu.setText(suhu+"°C");
           suhu++;
           if(suhu >= 32){
               suhu = 32;
           }
           
       }   
    }//GEN-LAST:event_btnsuhutambahActionPerformed
    private void btnsensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsensorActionPerformed
        if(stsMesin==true){
           if (sensor == false){
                sensor = true;
           lblsensor.setText("ON");
           lblsuhu.setText("MODE STAND BY");
           lbldeteksi.setText("0");
           lblhuman.setText("human");
       }  else{
           sensor = false;
           lblsensor.setText("OFF");
           lblsuhu.setText(".....");
           lbldeteksi.setText("....");
           barami.setValue(0);
      }
        }
    }//GEN-LAST:event_btnsensorActionPerformed

    private void sldamiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldamiStateChanged
 if(sensor==true){
    int sensorHuman = sldami.getValue();
    for (int i = 0; i <= sensorHuman; i++) {
                try {
                java.lang.Thread.sleep(0);
                barami.setValue(i);
                lbldeteksi.setText(Integer.toString(i));
                    if (sensorHuman >= 100) {
                        lblsuhu.setText("Mode Full *****");
                    } else if (sensorHuman >= 80){
                        lblsuhu.setText("Mode ****");
                    } else if (sensorHuman >= 50){
                        lblsuhu.setText("Mode ***");
                    } else if (sensorHuman >= 30){
                        lblsuhu.setText("Mode **");
                    } else if (sensorHuman >= 10){
                        lblsuhu.setText("Mode *");
                    } else if (sensorHuman >= 1){
                       lblsuhu.setText("Mode *");
                    } 
                    else {
                        lblsuhu.setText("Mode Stand by");
                    }
            } catch (Exception e) {
            }
        }
    }
    }//GEN-LAST:event_sldamiStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AC_Cerdas_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AC_Cerdas_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AC_Cerdas_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AC_Cerdas_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AC_Cerdas_Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barami;
    private javax.swing.JButton btnpower;
    private javax.swing.JButton btnsensor;
    private javax.swing.JButton btnsuhukurang;
    private javax.swing.JButton btnsuhutambah;
    private javax.swing.JButton btnswing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbldeteksi;
    private javax.swing.JLabel lblhuman;
    private javax.swing.JLabel lblsensor;
    private javax.swing.JLabel lblstatusmesin;
    private javax.swing.JLabel lblsuhu;
    private javax.swing.JLabel lblswing;
    private javax.swing.JSlider sldami;
    // End of variables declaration//GEN-END:variables
}
