package Press;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import report.FrmBukumatrix;
import report.FrmLaporan;


/**
 *
 * @author M.BAHRIL.I
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        vAnjungan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DPenulis = new javax.swing.JMenuItem();
        LapPenulis = new javax.swing.JMenuItem();
        Dmatrix = new javax.swing.JMenuItem();
        Lapmatrix = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jMenu1.setText("View");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        vAnjungan.setText("Anjungan Uniska Press");
        vAnjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAnjunganActionPerformed(evt);
            }
        });
        jMenu1.add(vAnjungan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        DPenulis.setText("Data Penulis");
        DPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPenulisActionPerformed(evt);
            }
        });
        jMenu2.add(DPenulis);

        LapPenulis.setText("Lap Data Penulis");
        LapPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPenulisActionPerformed(evt);
            }
        });
        jMenu2.add(LapPenulis);

        Dmatrix.setText("Data Matrix Buku");
        Dmatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DmatrixActionPerformed(evt);
            }
        });
        jMenu2.add(Dmatrix);

        Lapmatrix.setText("Lap Matrix Buku");
        Lapmatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapmatrixActionPerformed(evt);
            }
        });
        jMenu2.add(Lapmatrix);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void vAnjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAnjunganActionPerformed
       View vAnjungan = new View();
        jDesktopPane1.add(vAnjungan);
        vAnjungan.setVisible(true);
    }//GEN-LAST:event_vAnjunganActionPerformed

    private void DPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPenulisActionPerformed
        Penulis vPenulis = new Penulis();
        jDesktopPane1.add(vPenulis);
        vPenulis.setVisible(true);
    }//GEN-LAST:event_DPenulisActionPerformed

    private void LapPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPenulisActionPerformed
       FrmLaporan lap = new FrmLaporan();
       jDesktopPane1.add(lap);
        Dimension parentSize = this.getSize();
        Dimension childSize = lap.getSize();
        lap.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        lap.setVisible(true);
        lap.btampil.addActionListener(new java.awt.event.ActionListener() {
         @Override
           public void actionPerformed(ActionEvent ae) {
               lap.btampil.setText("Cetak Data Penulis"); //To change body of generated methods, choose Tools | Templates.
           }
        });   
    }//GEN-LAST:event_LapPenulisActionPerformed

    private void DmatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DmatrixActionPerformed
        MatrixBuku vMatrixBuku = new MatrixBuku();
        jDesktopPane1.add(vMatrixBuku);
        vMatrixBuku.setVisible(true);
    }//GEN-LAST:event_DmatrixActionPerformed

    private void LapmatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapmatrixActionPerformed
        FrmBukumatrix lap = new FrmBukumatrix();
       jDesktopPane1.add(lap);
        Dimension parentSize = this.getSize();
        Dimension childSize = lap.getSize();
        lap.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        lap.setVisible(true);
        lap.btampil.addActionListener(new java.awt.event.ActionListener() {
         @Override
           public void actionPerformed(ActionEvent ae) {
               lap.btampil.setText("Cetak Data Penulis"); //To change body of generated methods, choose Tools | Templates.
           }
        });
    }//GEN-LAST:event_LapmatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DPenulis;
    private javax.swing.JMenuItem Dmatrix;
    private javax.swing.JMenuItem LapPenulis;
    private javax.swing.JMenuItem Lapmatrix;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem vAnjungan;
    // End of variables declaration//GEN-END:variables
}
