/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Press;

/**
 *
 * @author M.BAHRIL.
 */
import javax.swing.JTable;
import java.sql.*;
import Class.jKoneksi;
import javax.swing.table.DefaultTableModel;

public class View extends javax.swing.JInternalFrame {
    private DefaultTableModel _Modtab;
    Connection _Cnn;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
       
        String[] setKolom = {"'NAMA'", "'NIDN'", "'ISBN'", "'JUDUL'", "'TAHUN'", "'JUMLAH HALAMAN'", "JUMLAH EKSEMPLAR", "NOMINAL"};
        _Modtab = new DefaultTableModel(null, setKolom) {
            Class[] types = new Class[]{
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
                 
            };
            
            public Class getColumClass(int columnIndex){
                return types[columnIndex];
            }
            
            public boolean isCellEditable(int row, int col){
                int kol = _Modtab.getColumnCount();
                return (col < kol) ? false : true;
            }     
        };
    jTable1.setModel(_Modtab); 
    loadDatatb1();
    }
    public void hapusRowData(){
                int row = _Modtab.getColumnCount();
                
                while (_Modtab.getRowCount() > 0){
                    _Modtab.setRowCount(0);
                }
    }
    private  void loadDatatb1(){
        String _sql = "";
        jKoneksi vConn = new jKoneksi();
        vConn.makeConnect();
        hapusRowData();
        try{
            _Cnn = vConn.vkoneksi;
            if (txt_cari.getText().equals("")){
                _sql = ""
                + "SELECT * FROM tb_penulis ";
            }else{
                _sql = ""
                        + "SELECT * FROM tb_penulis "
                        + "WHERE nama LIKE '%" + txt_cari.getText() + "%'"
                        + "OR isbn LIKE '%" + txt_cari.getText() + "%'"
                        + "OR tahun LIKE '%" + txt_cari.getText() + "%'"
                        + "OR nidn LIKE '%" + txt_cari.getText() + "%'"
                        + "OR judul LIKE '%" + txt_cari.getText() + "%'"
                        + "OR nominal LIKE '%" + txt_cari.getText() + "%'";
            }
            System.out.println(_sql);
            Statement st = _Cnn.createStatement();
            ResultSet res = st.executeQuery(_sql);
            while (res.next ()) {
                String nama = res.getString(1);
                String nidn = res.getString(2);
                String isbn = res.getString(3);
                String judul = res.getString(4);
                String tahun = res.getString(5);
                String hal = res.getString(6);
                String eks = res.getString(7);
                String nominal = res.getString(8);
                
                Object[] data = {nama, nidn, isbn, judul, tahun, hal, eks, nominal};
                _Modtab.addRow(data);
        
            }
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
        } catch (Exception e){
            System.out.println("Error" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Pencarian");

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        loadDatatb1();
    }//GEN-LAST:event_txt_cariKeyPressed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
       loadDatatb1();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        loadDatatb1();
    }//GEN-LAST:event_txt_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
