/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kipasangin;

/**
 *
 * @author M.BAHRIL.I
 */
public class remot_kipasangin extends javax.swing.JFrame {
    boolean stskipas = false;
    boolean stsswing = false;

    /** Creates new form remot_kipasangin */
    public remot_kipasangin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblpower = new javax.swing.JLabel();
        lblmode = new javax.swing.JLabel();
        lblswing = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnpower = new javax.swing.JButton();
        btnmode1 = new javax.swing.JButton();
        btnmode2 = new javax.swing.JButton();
        btnmode3 = new javax.swing.JButton();
        btnmode4 = new javax.swing.JButton();
        btnswingonoff = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("POWER            :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SWING             :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("KECEPATAN   :");

        lblpower.setForeground(new java.awt.Color(0, 0, 0));
        lblpower.setText("OFF");

        lblmode.setForeground(new java.awt.Color(0, 0, 0));
        lblmode.setText("MODE");

        lblswing.setForeground(new java.awt.Color(0, 0, 0));
        lblswing.setText("OFF");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REMOTE KIPAS ANGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblswing)
                    .addComponent(lblpower)
                    .addComponent(lblmode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblpower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblswing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblmode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnpower.setText("0/OFF");
        btnpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpowerActionPerformed(evt);
            }
        });

        btnmode1.setText("1");
        btnmode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmode1ActionPerformed(evt);
            }
        });

        btnmode2.setText("2");
        btnmode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmode2ActionPerformed(evt);
            }
        });

        btnmode3.setText("3");
        btnmode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmode3ActionPerformed(evt);
            }
        });

        btnmode4.setText("4");
        btnmode4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmode4ActionPerformed(evt);
            }
        });

        btnswingonoff.setText("SWING ON/OFF");
        btnswingonoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnswingonoffActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("M.BAHRIL ILMI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnmode1)
                            .addGap(18, 18, 18)
                            .addComponent(btnmode2)
                            .addGap(18, 18, 18)
                            .addComponent(btnmode3)
                            .addGap(18, 18, 18)
                            .addComponent(btnmode4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnpower)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnswingonoff))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpower)
                    .addComponent(btnswingonoff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmode1)
                    .addComponent(btnmode2)
                    .addComponent(btnmode3)
                    .addComponent(btnmode4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmode1ActionPerformed
        stskipas = true;
        lblpower.setText("ON");
        lblmode.setText("Lambat");
        
    }//GEN-LAST:event_btnmode1ActionPerformed

    private void btnmode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmode2ActionPerformed
        stskipas= true;
        lblpower.setText("ON");
        lblmode.setText("Sedang");
    }//GEN-LAST:event_btnmode2ActionPerformed

    private void btnmode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmode3ActionPerformed
         stskipas = true;
        lblpower.setText("ON");
        lblmode.setText("Kencang");
    }//GEN-LAST:event_btnmode3ActionPerformed

    private void btnmode4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmode4ActionPerformed
         stskipas = true;
        lblpower.setText("ON");
        lblmode.setText("Super Kencang");
    }//GEN-LAST:event_btnmode4ActionPerformed

    private void btnpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpowerActionPerformed
         stskipas = false;
        lblpower.setText("OFF");
        lblmode.setText("----");
        lblswing.setText("OFF");
    }//GEN-LAST:event_btnpowerActionPerformed

    private void btnswingonoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnswingonoffActionPerformed
        if(stskipas==true){
            if(stsswing==false){
                stsswing=true;
                lblswing.setText("ON");
            }else{
                stsswing=false;
                lblswing.setText("OFF");
            }
        }
    }//GEN-LAST:event_btnswingonoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remot_kipasangin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remot_kipasangin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remot_kipasangin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remot_kipasangin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remot_kipasangin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmode1;
    private javax.swing.JButton btnmode2;
    private javax.swing.JButton btnmode3;
    private javax.swing.JButton btnmode4;
    private javax.swing.JButton btnpower;
    private javax.swing.JButton btnswingonoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblmode;
    private javax.swing.JLabel lblpower;
    private javax.swing.JLabel lblswing;
    // End of variables declaration//GEN-END:variables

}
